version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: bistro
      POSTGRES_USER: bistro_user
      POSTGRES_PASSWORD: bistro_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: